spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        namespace: dev
      discovery:
        server-addr: localhost:8848
        namespace: dev